### ISSUE TITLE
Singularity question...

### ISSUE THREAD

**Issue by jgrn307** [SESYNC-ci/rslurm#22]
Hi, we're very interested in using your package, but we're running into an issue.  Our system uses a) modules to load R, and b) singularity which makes the apparent path-to-R a bit complicated -- we have to execute R via slurm using:

singularity exec [someimage] R --vanilla slurm.run.R

This could be tweaked pretty easily, I would imagine, via some options or allowing the use to customize a template.  Any thoughts on this?  Is there an easier solution to this problem I'm unaware of?

**Comment by pmarchand1** [comment]
In order to customize the generated scripts to your specific system, the easiest way is to edit the templates (look for the "templates" folder under rslurm in your package library). You should modify the line starting with `{{{rscript}}}` in both Bash file templates (`submit_sh.txt` and `submit_single_sh.txt`).

**Comment by jgrn307** [comment]
Phillippe -- thanks!  I assume they'll get overwritten in an update -- would you consider adding a parameter to allow a user to set the template file to some arbitrary location?

**Comment by itcarroll** [comment]
Related to #19

**Comment by qdread** [comment]
Closing this issue because slurm_apply and slurm_call now support custom templates (see pull request #47)
