### ISSUE TITLE
Tweak for specifying templates/Rscript location

### ISSUE THREAD

**Issue by jgrn307** [SESYNC-ci/rslurm#23]
(I'm a noobie at git, sorry if this isn't the right way to do this) -- I tweaked rslurm a bit to allow the user to specify the Rscript location (which was my issues) as well as specify specific templates:

https://github.com/jgrn307/rslurm.git

Feel free to incorporate these minor changes into the main rslurm!

**Comment by jgrn307** [comment]
I also just pushed a version that saves the slr_job as an .Rdata file to the submission folder so it can be restored easily by get_slurm_out (in situations where R stops running and you want to compile the results after the subjobs are finished)...

**Comment by itcarroll** [comment]
Thanks for your interest in contributing to rslurm. First, a couple GitHub procedural requests

1. Please create a branch in your fork with a relevant name for the feature you're proposing.
2. Issue a [pull request](https://help.github.com/articles/about-pull-requests/).
3. Minimize the diff as much as possible (i.e. eliminate white space only changes if you can).

We'll be able to tune your changes more easily as a pull request, because collaborators on the forked repo can (by default) push to your feature branch.

Second, a couple comments:

1. Can modifying the Rscript path be achieved by modifying the template, so that only one new parameter (path to template) need be introduced?
2. If a single line of code or two (i.e. `save(sjob, 'sjob.Rdata')`) can be equally effective inside and outside the package, I prefer to keep it outside. The user can already save slurm job objects as needed.
3. The Authors variable in the DESCRIPTION does not include all contributors, much like manuscript authorship. By issuing a PR, your contribution will be shown in the repository contributors.

Related to #22

**Comment by qdread** [comment]
Closing this issue because slurm_apply and slurm_call now support custom templates (see pull request #47) and the Rscript path can now be specified as an argument to slurm_apply and slurm_call (see pull request #45)
