### ISSUE TITLE
The `libPaths` argument to `slurm_apply` reverses the order of libraries used

### ISSUE THREAD

**Issue by Patrick330** [SESYNC-ci/rslurm#53]
When you pass multiple libraries to `libPaths`, the *slurm_run.R* file generated adds each one to the beginning of `.libPaths()` in the order they were passed. This results in the libraries being reversed in order in `.libPaths()`, which means that any packages are loaded from the last library in which they are available. This causes issues for users who, for example, operate on a shared cluster where there is both a centrally-managed package library and a personal package library and would prefer to load packages from one library rather than another.

**Comment by qdread** [comment]
Hi Patrick,
Thanks a lot for bringing this to my attention! I've reversed the order of the arguments in the relevant lines of the template, so that multiple paths are added to `.libPaths()` at the end rather than the beginning. [See this commit](https://github.com/SESYNC-ci/rslurm/commit/9d979d3fe4fab17746469c3a232bfd1ea0d2ddba). Please confirm that this resolves your issue.
best,
Quentin

**Comment by Patrick330** [comment]
Hi Quentin,
Yes, I believe that will fix the issue. Thank you!

Patrick

**Comment by qdread** [comment]
Excellent, thanks again for your help. Closing the issue.
