### ISSUE TITLE
allow Spatial*DataFrame as param

### ISSUE THREAD

**Issue by itcarroll** [SESYNC-ci/rslurm#6]
It would be nice to directly pass other objects that inherit from the data.frame class, such as a SpatialPolygonsDataFrame. Currently the required matching between column names in the params data.frame and the argument names in the function gets in the way.

**Comment by pmarchand1** [comment]
Currently, when the function doesn't need the spatial information, you can just pass the '@data' part of the spatial object, and if the spatial information is needed, it's easier to add the whole spatial object to "add_obj" and make a function that iterates on the index. 

I haven't tried it yet, but the sfr (simple features in R) package was created to represent R spatial data in a more standardized way, similar to geodatabases: http://edzer.github.io/sfr/articles/ . Since the spatial info. is in its own column, it might be more compatible with rslurm and other "map"-type operations.

**Comment by itcarroll** [comment]
This looks promising, thanks. I have to wait until we upgrade to GDAL >= 2.0.0 on the cluster (so we can use the sf package) to test whether using the geom column of a sf data.frame will eliminate any need to modify the package.

**Comment by pmarchand1** [comment]
I just tested the sf compatibility with the test table from postGIStools (country table). I selected the name, population and geom columns and tried a simple function that calculates population density using st_area. So it seems to be compatible with sf data types, and this issue would be solved.
