### ISSUE TITLE
Unable to retrieve output

### ISSUE THREAD

**Issue by ekernf01** [SESYNC-ci/rslurm#67]
I'm trying to run the example from the vignette, but with `submit=T` and `wait=T`. 

```
test_func <- function(par_mu, par_sd) {
  samp <- rnorm(10^6, par_mu, par_sd)
  c(s_mu = mean(samp), s_sd = sd(samp))
}
pars <- data.frame(par_mu = 1:10,
                   par_sd = seq(0.1, 1, length.out = 10))
sjob <- rslurm::slurm_apply(test_func, pars, jobname = 'test_apply',
                    nodes = 2, cpus_per_node = 2, submit = T)
res <- rslurm::get_slurm_out(sjob, outtype = 'table', wait = T)
```

I see a warning:

```
Warning message:
In rslurm::get_slurm_out(sjob, outtype = "table", wait = T) :
  The following files are missing: results_0.RDS, results_1.RDS
```

and `res` is `NA`. I'm using the `rslurm 0.5.0`, `R 4.0.2`, `slurm 17.11.12`, and `CentOS Linux 7 (Core)  x86_64, linux-gnu`. Can you see what the issue is, and do you need any other info to reproduce this problem? Thanks!

Possible related to:

https://github.com/SESYNC-ci/rslurm/issues/17

https://github.com/SESYNC-ci/rslurm/issues/58

**Comment by qdread** [comment]
I can't reproduce your error. The missing files warning would occur when the job is not complete so I would guess that if you run that code block all at once, the `wait = TRUE` argument is failing to wait for the job to complete. So `get_slurm_out` executes before the job is complete. 

It's possible there may be an incompatibility with newer versions of slurm (we are running 15.08.7) but we are waiting on a system upgrade which should happen in the next few weeks. At that point I will be able to test on a newer version of slurm. See #64 which refers to `rslurm:::wait_for_job()` which is called internally by `get_slurm_out` if `wait = TRUE`. We have a potential fix ready, but can't test until our system is upgraded. So we should be able to address your problem soon. I will revisit shortly. Sorry for the inconvenience and thanks for your patience.

**Comment by qdread** [comment]
Pull request #65 should resolve this issue. Please try installing the dev version with `remotes::install_github('SESYNC-ci/rslurm')` and let me know whether `get_slurm_out()` waits for the job to finish running, as intended. Hopefully soon we will get a new version on CRAN with this fix.

**Comment by ekernf01** [comment]
Works like a charm!

**Comment by masonyoungblood** [comment]
I'm encountering the same issue (using the the dev version installed, as recommended by by @qdread). The R script runs perfectly with 10,000 iterations, but fails with the same "following files are missing" warning message (as with @ekernf01) when I increase it to 200,000 iterations. Is it possible that there is another incompatibility? I'm using slurm version 17.11.2.

**Comment by qdread** [comment]
Hi @masonyoungblood thanks for your comment. At the moment the dev version has no meaningful differences from the CRAN version so that shouldn't be the problem. Currently I am testing this on slurm 21.08.5 and do not see an error when running the vignette code. Are you trying to run that code or something else? Would it be possible for you to share the exact code that produces the error so I can take a closer look?

I checked the [archived sbatch documentation from slurm 17.11.2](https://slurm.schedmd.com/archive/slurm-17.11.2/sbatch.html) and it looks like the `--wait` option to `sbatch` was already implemented at that time so I don't think it should be a version issue.  Although I cannot test it, I think `get_slurm_out( ... , wait= TRUE)` should be compatible with any version of slurm 16.05 or later.

**Comment by understorey** [comment]
I am also having the same issue, is there a workaround to "force" it to wait?
